accessing workloads
franciscoWorkloadJSON

	^ '{
  "user": {
    "self": "http://issues.mercap.net:8080/rest/api/2/user?username=fortiz",
    "name": "fortiz",
    "key": "fortiz",
    "displayName": "Francisco Ortiz",
    "avatar": "http://issues.mercap.net:8080/secure/useravatar?size=small&ownerId=fortiz&avatarId=13500"
  },
  "status": "open",
  "workedSeconds": 244800,
  "submittedSeconds": 0,
  "requiredSeconds": 547200,
  "requiredSecondsRelativeToday": 345600,
  "period": {
    "periodView": "DISABLED",
    "dateFrom": "2017-12-01",
    "dateTo": "2017-12-31"
  },
  "smartDateString": "Current month",
  "worklogs": {
    "href": "http://issues.mercap.net:8080/rest/tempo-timesheets/3/worklogs?username=fortiz&dateFrom=2017-12-01&dateTo=2017-12-31"
  }
}'